const destinations=[
  {id:1,name:"Hotel Majapahit",tag:"Art Deco",type:"art deco",emoji:"🏛️",addr:"Jl. Tunjungan No.65, Genteng",price:"Rp 35.000",priceNum:35000,hours:"08.00–20.00 WIB",rating:"4.9 ★",desc:"Salah satu landmark kolonial paling ikonik di Surabaya. Dibangun 1910 dengan gaya art deco Belanda, hotel ini menjadi saksi insiden perobekan bendera 1945 dalam sejarah kemerdekaan Indonesia.",transport:["Angkot Line C2 — stop Tunjungan","Trans Semanggi — halte Balai Kota (~5 menit)","Grab / Gojek — direkomendasikan"],reviews:[{u:"Sinta R.",s:"★★★★★",t:"Fasad art deco-nya luar biasa indah. Wajib dikunjungi!"},{u:"Bimo A.",s:"★★★★☆",t:"Lobbynya megah dan penuh sejarah. Sangat berkesan."}]},
  {id:2,name:"House of Sampoerna",tag:"Kolonial",type:"colonial",emoji:"🏭",addr:"Jl. Taman Sampoerna No.6, Krembangan",price:"Gratis",priceNum:0,hours:"09.00–22.00 WIB",rating:"4.8 ★",desc:"Kompleks bangunan kolonial Belanda yang terawat indah sejak 1862. Kini menjadi museum, pusat budaya, dan kafe yang mendokumentasikan sejarah Surabaya lewat lensa merek tembakau paling ikonik Indonesia.",transport:["Angkot Line B — stop Pasar Atom","Trans Semanggi — halte Rajawali","Heritage Walk dari Jembatan Merah (~10 menit)"],reviews:[{u:"Dian P.",s:"★★★★★",t:"Museum sangat terawat. Arsitektur pabrik tuanya autentik."},{u:"Arif W.",s:"★★★★☆",t:"Kafenya enak, pemandangan ke bangunan kunonya bagus."}]},
  {id:3,name:"Balai Kota Surabaya",tag:"Pemerintahan",type:"government",emoji:"🏛️",addr:"Jl. Walikota Mustajab No.1, Genteng",price:"Gratis",priceNum:0,hours:"08.00–16.00 (hari kerja)",rating:"4.6 ★",desc:"Dibangun 1923, Balai Kota adalah contoh arsitektur kolonial Belanda dengan kolom neoklasik yang megah. Mencerminkan ambisi perencanaan kota era kolonial yang masih terawat hingga kini.",transport:["Trans Semanggi — halte Balai Kota (langsung)","Angkot Line A & D","Parkir tersedia di lokasi"],reviews:[{u:"Maya S.",s:"★★★★☆",t:"Bangunannya megah. Area sekitarnya nyaman untuk jalan kaki."},{u:"Hendra T.",s:"★★★★★",t:"Wajib untuk pecinta arsitektur kolonial!"}]},
  {id:4,name:"Masjid Cheng Hoo",tag:"Religi",type:"religious",emoji:"🕌",addr:"Jl. Gading No.2, Ketabang",price:"Gratis",priceNum:0,hours:"Buka 24 jam",rating:"4.7 ★",desc:"Masjid unik yang memadukan arsitektur pagoda China dengan elemen Islam, dibangun 2002 sebagai simbol harmoni multikultural. Dinamai dari laksamana Muslim China legendaris, Zheng He.",transport:["Angkot Line F — stop Genteng","Grab/Gojek dari pusat kota (~10 menit)","Parkir tersedia"],reviews:[{u:"Rina K.",s:"★★★★★",t:"Perpaduan arsitektur China dan Islam yang sangat indah."},{u:"Fajar L.",s:"★★★★☆",t:"Bersih, tenang, dan sangat fotogenik."}]},
  {id:5,name:"Gedung Internatio",tag:"Kolonial",type:"colonial",emoji:"🏢",addr:"Jl. Rajawali No.3, Krembangan",price:"Rp 15.000",priceNum:15000,hours:"09.00–17.00 WIB",rating:"4.5 ★",desc:"Dibangun 1925, Gedung Internatio adalah bangunan neoklasik kolonial yang megah — dulu sebagai rumah dagang besar. Kolom-kolomnya dan ornamen plasterwork menjadikannya salah satu contoh arsitektur komersial terbaik di Jawa Timur.",transport:["Trans Semanggi — halte Rajawali (langsung)","Angkot Line B","5 menit jalan dari House of Sampoerna"],reviews:[{u:"Laras M.",s:"★★★★★",t:"Kolom-kolomnya megah. Saksi bisu sejarah perdagangan Surabaya."},{u:"Doni S.",s:"★★★★☆",t:"Interior menarik, ada pameran sejarah di dalamnya."}]},
  {id:6,name:"Gereja Kepanjen",tag:"Religi",type:"religious",emoji:"⛪",addr:"Jl. Kepanjen No.4, Krembangan",price:"Gratis",priceNum:0,hours:"06.00–19.00 WIB",rating:"4.6 ★",desc:"Salah satu gereja Katolik tertua di Indonesia (1899). Fasad neo-Gotik, jendela mawar, dan menara kembarnya menjadikannya karya arsitektur gerejawi Eropa yang luar biasa di tengah Surabaya.",transport:["Angkot Line C — stop Kepanjen","Jarak jalan dari Alun-Alun Surabaya","Grab/Gojek — turun di Jl. Kepanjen"],reviews:[{u:"Clara N.",s:"★★★★★",t:"Sangat indah, seperti di Eropa. Bangunan tuanya sangat terawat."}]}
];

const tourPackages=[
  {id:'t1',name:"Tur Kota Lama Surabaya",emoji:"🚶",desc:"Jelajahi kawasan Kota Lama bersama guide sejarah berpengalaman. Kunjungi 4 bangunan ikonik dalam 3 jam dengan penjelasan mendalam tentang arsitektur dan sejarahnya.",features:["3 jam walking tour berpemandu","Kunjungi 4 bangunan bersejarah","Akses area eksklusif","Snack & minuman disediakan","Maks. 10 orang per sesi"],price:150000,priceLabel:"Rp 150.000",unit:"per orang",featured:false,badge:null},
  {id:'t2',name:"Tur Malam Kolonial Premium",emoji:"🌙",desc:"Rasakan keindahan bangunan kolonial Surabaya di bawah cahaya malam. Tur eksklusif dengan pencahayaan dramatis dan sesi foto profesional.",features:["3,5 jam night walking tour","Fotografer profesional ikut serta","Kunjungi 5 spot ikonik malam hari","Welcome drink & snack premium","Grup privat — maks. 8 orang"],price:250000,priceLabel:"Rp 250.000",unit:"per orang",featured:true,badge:"Terpopuler"},
  {id:'t3',name:"Paket Keluarga Arsitektur",emoji:"👨‍👩‍👧‍👦",desc:"Paket tur ramah keluarga dengan aktivitas edukatif untuk anak-anak. Termasuk buku mewarnai arsitektur, kuis sejarah, dan sertifikat Penjelajah Muda Surabaya.",features:["2 jam tur keluarga berpemandu","Kit aktivitas anak (buku mewarnai, kuis)","Sertifikat penjelajah untuk anak","Kunjungi 3 destinasi utama","Cocok untuk anak 6–14 tahun"],price:120000,priceLabel:"Rp 120.000",unit:"per keluarga (maks. 5 orang)",featured:false,badge:null}
];

const ongoingEvts=[
  {day:"28",mon:"MAR",name:"Pameran Foto Arsitektur Kota Lama",venue:"Gedung Internatio, Rajawali",detail:"Pameran fotografi bangunan cagar budaya kolonial",price:"Rp 25.000",priceNum:25000},
  {day:"01",mon:"APR",name:"Festival Heritage Walk Surabaya",venue:"Kawasan Kota Lama",detail:"Tur jalan kaki berpemandu — setiap akhir pekan, 07.00 WIB",price:"Rp 50.000",priceNum:50000}
];

const upcomingEvts=[
  {day:"10",mon:"APR",name:"Surabaya Architecture Week 2025",venue:"Balai Kota & sekitarnya",detail:"Festival arsitektur tahunan: talks, pameran & tur",price:"Gratis – Rp 100.000"},
  {day:"20",mon:"APR",name:"Night Tour: Kolonial Surabaya",venue:"Jl. Tunjungan & Jl. Rajawali",detail:"Tur malam bangunan kolonial berlampu",price:"Rp 75.000"},
  {day:"05",mon:"MAY",name:"Workshop Sketching Bangunan Tua",venue:"House of Sampoerna",detail:"Urban sketching workshop untuk pecinta arsitektur",price:"Rp 150.000"}
];